export const types = {
  FETCH_ALL_JOBS: "FETCH_ALL_JOBS",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SELECTED_NEW_JOB: 'SELECTED_NEW_JOB',
  SELECT_JOB_SUBPAGE: "SELECT_JOB_SUBPAGE",
  SWITCH_THEME: 'SWITCH_THEME',
  API: "API",
  API_START: "API_START",
  API_END: "API_END",
  ACCESS_DENIED: "ACCESS_DENIED",
  API_ERROR: "API_ERROR",
};
