export const types = {
  FETCH_ALL_JOBS: "FETCH_ALL_JOBS",
  SET_CURRENT_USER: "SET_CURRENT_USER",

  API: "API",
  API_START: "API_START",
  API_END: "API_END",
  ACCESS_DENIED: "ACCESS_DENIED",
  API_ERROR: "API_ERROR",
};
